%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/Lipid4/lipid4.tmp
%
% Auto-generated by MATLAB on 10-Dec-2019 09:27:46
clear all
close all
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Mean", "Variance", "Var3"];
opts.SelectedVariableNames = ["Mean", "Variance"];
opts.VariableTypes = ["double", "double", "char"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Mean", "TrimNonNumeric", true);
opts = setvaropts(opts, "Mean", "ThousandsSeparator", ",");

% Import the data
lipid6_6 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/lipid6_0.6/lipid6.tmp", opts);
lipid6_8 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/lipid6_0.8/lipid6.tmp", opts);
lipid6_9 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/lipid6_0.9/lipid6.tmp", opts);
lipid6_66 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/lipid6_0.66/lipid6.tmp", opts);
lipid6_75 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/lipid6_0.75/lipid6.tmp", opts);
lipid6_11 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/lipid6_1.1/lipid6.tmp", opts);
lipid6_125 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/lipid6FracTest/lipid6_1.25/lipid6.tmp", opts);


%% Clear temporary variables
clear opts

%% Plot the variationsin Bilayer Surface Tension over time
x_axis = [1000:1000:20000];

figure
plot(x_axis(5:end), lipid6_11.Mean(5:end), 'LineWidth', 5);
hold on;
plot(x_axis(5:end), lipid6_125.Mean(5:end), 'LineWidth', 5);
plot(x_axis(5:end), lipid6_6.Mean(5:end), 'LineWidth', 5);
plot(x_axis(5:end), lipid6_66.Mean(5:end), 'LineWidth', 5);
plot(x_axis(5:end), lipid6_75.Mean(5:end), 'LineWidth', 5);
plot(x_axis(5:end), lipid6_8.Mean(5:end), 'LineWidth', 5);
plot(x_axis(5:end), lipid6_9.Mean(5:end), 'LineWidth', 5);
grid on;
title('Lipid 6 - Various fraction');
legend('0.6', '0.8', '0.9', '0.66', '0.75', '1.1', '1.25');
xlabel('Time');
ylabel('Bilayer Surface Tension');
set(gca,'FontSize',20);

