%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/archangel/Documents/EPFL/Computational Cell Biology/Project/IrisProject/Lipid4/lipid4.tmp
%
% Auto-generated by MATLAB on 10-Dec-2019 09:27:46
clear all
close all
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Mean", "Variance", "Var3"];
opts.SelectedVariableNames = ["Mean", "Variance"];
opts.VariableTypes = ["double", "double", "char"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Mean", "TrimNonNumeric", true);
opts = setvaropts(opts, "Mean", "ThousandsSeparator", ",");

% Import the data
lipid4 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/IrisProject/lipid4/lipid4.tmp", opts);
lipid6 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/IrisProject/lipid6/lipid6.tmp", opts);
lipid8 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/IrisProject/lipid8/lipid8.tmp", opts);
lipid10 = readtable("/home/archangel/Documents/EPFL/Computational Cell Biology/Project/IrisProject/lipid10/lipid10.tmp", opts);


%% Clear temporary variables
clear opts

%% Plot the variationsin Bilayer Surface Tension over time
x_axis = [1000:1000:20000];

figure
plot(x_axis(5:end), lipid4.Mean(5:end), 'LineWidth', 5);
hold on;
plot(x_axis(5:end), lipid6.Mean(5:end), 'LineWidth', 5);
plot(x_axis(5:end), lipid8.Mean(5:end), 'LineWidth', 5);
plot(x_axis(5:end), lipid10.Mean(5:end), 'LineWidth', 5);
grid on;
legend('Lipid 4', 'Lipid 6', 'Lipid 8', 'Lipid 10');
xlabel('Time');
ylabel('Bilayer Surface Tension');
set(gca,'FontSize',50);

